client localhost {
	ipaddr = 127.0.0.1
	secret = radius123
	require_message_authenticator = no
	limit_proxy_state = no
	nas_type = other
}

client localhost_ipv6 {
	ipv6addr = ::1
	secret = radius123
	shortname = localhost_ipv6
}

client dockernet {
	ipaddr = 172.16.0.0/12
	secret = vHnTjrB37vgp
	require_message_authenticator = no
	limit_proxy_state = no
	nas_type = other
	shortname = dockernet
}
