version: "3"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${DOZZLE_PORT:-8888}:8080"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_HEADER_USER: admin
      DOZZLE_NO_ANALYTICS: "true"
    restart: always
